name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
        arch: [x64, Win32]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake -B Build -A ${{matrix.arch}}

    - name: Build
      run: |
        cmake --build Build --config ${{matrix.config}}

    - name: Test
      working-directory: Build
      run: |
        ctest -C ${{matrix.config}} --output-on-failure --verbose

  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    # Tests are disabled until we can fix the build errors.
    - name: Configure CMake
      run: |
        cmake -B Build -G Xcode -D ARCANA_TESTS=OFF

    - name: Build
      run: |
        cmake --build Build --config ${{matrix.config}}

    # - name: Test
    #   working-directory: Build
    #   run: |
    #     ctest -C ${{matrix.config}} --output-on-failure --verbose

  ios:
    name: iOS
    runs-on: macos-latest
    strategy:
      matrix:
        config: [Debug, Release]
        platform: [iphoneos, iphonesimulator]

    steps:
    - uses: actions/checkout@v4

    # Tests are disabled until we can fix the build errors and figure out how to run them on the simulator.
    - name: Configure CMake for iOS
      run: |
        cmake -B Build -G Xcode \
          -D CMAKE_SYSTEM_NAME=iOS \
          -D CMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
          -D CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO \
          -D CMAKE_IOS_INSTALL_COMBINED=YES \
          -D ARCANA_TESTS=OFF

    - name: Build
      run: |
        cmake --build Build --config ${{matrix.config}}

      # - name: Test
      #   working-directory: Build
      #   run: |
      #     ctest -C ${{matrix.config}} --output-on-failure --verbose

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release]
        compiler: [gcc-11, clang-14]
        include:
          - compiler: gcc-11
            cc: gcc-11
            cxx: g++-11
          - compiler: clang-14
            cc: clang-14
            cxx: clang++-14

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{matrix.cc }} ${{ matrix.cxx}}

    # Tests are disabled until we can fix the build errors.
    - name: Configure CMake
      run: |
        cmake -B Build \
          -D CMAKE_BUILD_TYPE=${{matrix.config}} \
          -D CMAKE_C_COMPILER=${{matrix.cc}} \
          -D CMAKE_CXX_COMPILER=${{matrix.cxx}} \
          -D ARCANA_TESTS=OFF

    - name: Build
      run: |
        cmake --build Build --config ${{matrix.config}}

      # - name: Test
      #   working-directory: Build
      #   run: |
      #     ctest -C ${{matrix.config}} --output-on-failure --verbose
